import os

OPENAI_API_KEY = 'YOUR_OPENAI_API_KEY'
ACTIVELOOP_TOKEN = "YOUR_ACTIVELOOP_TOKEN"

ACTIVELOOP_ID = 'ID'

os.environ["OPENAI_API_KEY"] = OPENAI_API_KEY
os.environ["ACTIVELOOP_TOKEN"] = ACTIVELOOP_TOKEN


